In [ ]:
from geopy.geocoders import Nominatim
from geopy.distance import geodesic as GD

geolocator = Nominatim(user_agent="primsAlgo")
list=["Nagpur","Mumbai","Nashik","Pune"]

In [ ]:
city=[]
latitude=[]
longitude=[]
for i in range(4):
  location = geolocator.geocode(list[i])
  latitude.append(location.latitude)
  longitude.append(location.longitude)
for j in range(4):
  city.append((latitude[j], longitude[j]))

In [ ]:
latitude

[21.1498134, 18.9733536, 20.0112475, 18.521428]

In [ ]:
longitude

[79.0820556, 72.82810491917377, 73.7902364, 73.8544541]

In [ ]:
city

[(21.1498134, 79.0820556),
 (18.9733536, 72.82810491917377),
 (20.0112475, 73.7902364),
 (18.521428, 73.8544541)]

In [ ]:
import numpy as np
Out=[]
for i in range(4):
  dist=[]
  for j in range(4):
    d=(GD(city[i],city[j]).miles)
    dist.append(d)
  Out.append(dist)
# Creating NumPy array
arr = np.array(Out)

# Reshaping array to n x m matrix
res = arr.reshape(4, 4)

# printing result
print("Constructed Matrix : \n" + str(res))

Constructed Matrix : 
[[  0.         433.14254286 351.63117602 385.27630868]
 [433.14254286   0.          95.05472496  74.08556961]
 [351.63117602  95.05472496   0.         102.55989455]
 [385.27630868  74.08556961 102.55989455   0.        ]]


In [ ]:
Out

[[0.0, 433.1425428591388, 351.63117601750474, 385.2763086761522],
 [433.1425428591388, 0.0, 95.05472496111854, 74.08556960975572],
 [351.63117601750474, 95.05472496111854, 0.0, 102.55989455322408],
 [385.2763086761522, 74.08556960975572, 102.55989455322408, 0.0]]

In [ ]:
import numpy as np

In [ ]:
cost=res
print(cost)
cost = cost.astype(np.int32)
print(cost)

[[  0.         433.14254286 351.63117602 385.27630868]
 [433.14254286   0.          95.05472496  74.08556961]
 [351.63117602  95.05472496   0.         102.55989455]
 [385.27630868  74.08556961 102.55989455   0.        ]]
[[  0 433 351 385]
 [433   0  95  74]
 [351  95   0 102]
 [385  74 102   0]]


In [ ]:
n=4

In [ ]:
edges = []
print(edges)

[]


In [ ]:
for i in range(n):
    for j in range(n):
        if i<j:
            edges.append([i,j,cost[i][j]])
print(edges)

[[0, 1, 433], [0, 2, 351], [0, 3, 385], [1, 2, 95], [1, 3, 74], [2, 3, 102]]


In [ ]:
edges = np.array(edges)

In [ ]:
edges = edges[edges[:,2].argsort()]

In [ ]:
print(edges)

[[  1   3  74]
 [  1   2  95]
 [  2   3 102]
 [  0   2 351]
 [  0   3 385]
 [  0   1 433]]


In [ ]:
def findParent(u,parent):
  if parent[u-1] == -1:
    return u-1
  return findParent(parent[u-1],parent)

In [ ]:
def Union(u,v,parent):
  parent[v-1] = u-1
  return

In [ ]:
t = np.array([[0]*3 for i in range(n-1)])
t

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
parent = [-1]*n
parent
edges.shape

(6, 3)

In [ ]:
def Kruskal(E,n,t):
  parent = [-1]*n
  i = 0
  j = -1 #traversing the edge matrix
  mincost = 0
  while (i < n-1) and (i < E.shape[0]):
    j+=1
    u = E[j][0]
    v = E[j][1]
    p = findParent(E[j][0],parent)
    q = findParent(E[j][1],parent)

    if p != q:
      i+=1
      t[i-1][0] = u
      t[i-1][1] = v
      t[i-1][2] = E[j][2]
      mincost+=E[j][2]
      Union(u,v,parent)

  if i!=n-1:
    print("No spanning tree")
  else:
    print("Mincost : ",mincost)
    print(t)
Kruskal(edges,n,t)

Mincost :  602
[[  1   3  74]
 [  1   2  95]
 [  0   1 433]]
