In [1]:
from geopy.geocoders import Nominatim
from geopy.distance import geodesic as GD

geolocator = Nominatim(user_agent="primsAlgo")
list=["Nagpur","Mumbai","Nashik","Pune","Goa","Kolkata"]

In [2]:
city=[]
latitude=[]
longitude=[]
for i in range(6):
  location = geolocator.geocode(list[i])
  latitude.append(location.latitude)
  longitude.append(location.longitude)
for j in range(6):
  city.append((latitude[j], longitude[j]))

In [3]:
latitude

[21.1498134, 19.08157715, 20.0112475, 18.521428, 15.3004543, 22.5726459]

In [4]:
longitude

[79.0820556, 72.88662753964906, 73.7902364, 73.8544541, 74.0855134, 88.3638953]

In [5]:
city

[(21.1498134, 79.0820556),
 (19.08157715, 72.88662753964906),
 (20.0112475, 73.7902364),
 (18.521428, 73.8544541),
 (15.3004543, 74.0855134),
 (22.5726459, 88.3638953)]

In [6]:
import numpy as np
Out=[]
for i in range(6):
  dist=[]
  for j in range(6):
    d=(GD(city[i],city[j]).miles)
    dist.append(d)
  Out.append(dist)
# Creating NumPy array
arr = np.array(Out)

# Reshaping array to n x m matrix
res = arr.reshape(6, 6)

# printing result
print("Constructed Matrix : \n" + str(res))

Constructed Matrix : 
[[   0.          426.91130742  351.63117602  385.27630868  519.1781416
   604.01161607]
 [ 426.91130742    0.           86.95465885   74.18357141  271.82331855
  1028.8584794 ]
 [ 351.63117602   86.95465885    0.          102.55989455  324.55234375
   955.61567144]
 [ 385.27630868   74.18357141  102.55989455    0.          222.02158791
   980.04198216]
 [ 519.1781416   271.82331855  324.55234375  222.02158791    0.
  1058.98946969]
 [ 604.01161607 1028.8584794   955.61567144  980.04198216 1058.98946969
     0.        ]]


In [7]:
Out

[[0.0,
  426.9113074164837,
  351.63117601750474,
  385.2763086761522,
  519.1781416000524,
  604.0116160731279],
 [426.9113074164837,
  0.0,
  86.95465884996,
  74.1835714099585,
  271.82331855241404,
  1028.858479402171],
 [351.63117601750474,
  86.95465884996,
  0.0,
  102.55989455322408,
  324.5523437486846,
  955.6156714446245],
 [385.2763086761522,
  74.1835714099585,
  102.55989455322408,
  0.0,
  222.02158790787772,
  980.0419821624937],
 [519.1781416000524,
  271.82331855241404,
  324.5523437486846,
  222.02158790787772,
  0.0,
  1058.9894696910126],
 [604.0116160731279,
  1028.858479402171,
  955.6156714446245,
  980.0419821624937,
  1058.9894696910126,
  0.0]]

In [8]:
import numpy as np

In [9]:
cost=res
print(cost)
cost = cost.astype(np.int32)
print(cost)

[[   0.          426.91130742  351.63117602  385.27630868  519.1781416
   604.01161607]
 [ 426.91130742    0.           86.95465885   74.18357141  271.82331855
  1028.8584794 ]
 [ 351.63117602   86.95465885    0.          102.55989455  324.55234375
   955.61567144]
 [ 385.27630868   74.18357141  102.55989455    0.          222.02158791
   980.04198216]
 [ 519.1781416   271.82331855  324.55234375  222.02158791    0.
  1058.98946969]
 [ 604.01161607 1028.8584794   955.61567144  980.04198216 1058.98946969
     0.        ]]
[[   0  426  351  385  519  604]
 [ 426    0   86   74  271 1028]
 [ 351   86    0  102  324  955]
 [ 385   74  102    0  222  980]
 [ 519  271  324  222    0 1058]
 [ 604 1028  955  980 1058    0]]


In [10]:
n=6

In [11]:
edges = []
print(edges)

[]


In [12]:
for i in range(n):
    for j in range(n):
        if i<j:
            edges.append([i,j,cost[i][j]])
print(edges)

[[0, 1, 426], [0, 2, 351], [0, 3, 385], [0, 4, 519], [0, 5, 604], [1, 2, 86], [1, 3, 74], [1, 4, 271], [1, 5, 1028], [2, 3, 102], [2, 4, 324], [2, 5, 955], [3, 4, 222], [3, 5, 980], [4, 5, 1058]]


In [13]:
edges = np.array(edges)

In [14]:
edges = edges[edges[:,2].argsort()]

In [15]:
def findParent(u,parent):
  if parent[u-1] == -1:
    return u-1
  return findParent(parent[u-1],parent)

In [16]:
def Union(u,v,parent):
  parent[v-1] = u-1
  return

In [17]:
t = np.array([[0]*3 for i in range(n-1)])
t

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
parent = [-1]*n
parent
edges.shape

(15, 3)

In [19]:
def Kruskal(E,n,t):
  parent = [-1]*n
  i = 0
  j = -1 #traversing the edge matrix
  mincost = 0
  while (i < n-1) and (i < E.shape[0]):
    j+=1
    u = E[j][0]
    v = E[j][1]
    p = findParent(E[j][0],parent)
    q = findParent(E[j][1],parent)

    if p != q:
      i+=1
      t[i-1][0] = u
      t[i-1][1] = v
      t[i-1][2] = E[j][2]
      mincost+=E[j][2]
      Union(u,v,parent)

  if i!=n-1:
    print("No spanning tree")
  else:
    print("Mincost : ",mincost)
    print(t)
Kruskal(edges,n,t)

Mincost :  1079
[[  1   3  74]
 [  1   2  86]
 [  3   4 222]
 [  1   4 271]
 [  0   1 426]]
