In [1]:
from geopy.geocoders import Nominatim
from geopy.distance import geodesic as GD

geolocator = Nominatim(user_agent="primsAlgo")
list=["Nagpur","Mumbai","Nashik","Pune","Goa","Kolkata","Bangalore","Hyderabad"]

In [2]:
city=[]
latitude=[]
longitude=[]
for i in range(8):
  location = geolocator.geocode(list[i])
  latitude.append(location.latitude)
  longitude.append(location.longitude)
for j in range(8):
  city.append((latitude[j], longitude[j]))

In [3]:
latitude

[21.1498134,
 18.9733536,
 20.0112475,
 18.521428,
 15.3004543,
 22.5726459,
 12.9767936,
 17.360589]

In [4]:
longitude

[79.0820556,
 72.82810491917377,
 73.7902364,
 73.8544541,
 74.0855134,
 88.3638953,
 77.590082,
 78.4740613]

In [5]:
city

[(21.1498134, 79.0820556),
 (18.9733536, 72.82810491917377),
 (20.0112475, 73.7902364),
 (18.521428, 73.8544541),
 (15.3004543, 74.0855134),
 (22.5726459, 88.3638953),
 (12.9767936, 77.590082),
 (17.360589, 78.4740613)]

In [6]:
import numpy as np
Out=[]
for i in range(8):
  dist=[]
  for j in range(8):
    d=(GD(city[i],city[j]).miles)
    dist.append(d)
  Out.append(dist)
# Creating NumPy array
arr = np.array(Out)

# Reshaping array to n x m matrix
res = arr.reshape(8, 8)

# printing result
print("Constructed Matrix : \n" + str(res))

Constructed Matrix : 
[[   0.          433.14254286  351.63117602  385.27630868  519.1781416
   604.01161607  570.62258475  263.64143978]
 [ 433.14254286    0.           95.05472496   74.08556961  265.90267576
  1034.62751918  519.8317633   387.37657718]
 [ 351.63117602   95.05472496    0.          102.55989455  324.55234375
   955.61567144  545.37116796  357.02193638]
 [ 385.27630868   74.08556961  102.55989455    0.          222.02158791
   980.04198216  455.15431843  314.39083762]
 [ 519.1781416   265.90267576  324.55234375  222.02158791    0.
  1058.98946969  284.23565093  323.97593813]
 [ 604.01161607 1034.62751918  955.61567144  980.04198216 1058.98946969
     0.          968.38565007  736.0410313 ]
 [ 570.62258475  519.8317633   545.37116796  455.15431843  284.23565093
   968.38565007    0.          307.13124961]
 [ 263.64143978  387.37657718  357.02193638  314.39083762  323.97593813
   736.0410313   307.13124961    0.        ]]


In [7]:
Out

[[0.0,
  433.1425428591388,
  351.63117601750474,
  385.2763086761522,
  519.1781416000524,
  604.0116160731279,
  570.6225847450158,
  263.641439782533],
 [433.1425428591388,
  0.0,
  95.05472496111854,
  74.08556960975572,
  265.90267575634203,
  1034.6275191801828,
  519.8317632993619,
  387.3765771801249],
 [351.63117601750474,
  95.05472496111854,
  0.0,
  102.55989455322408,
  324.5523437486846,
  955.6156714446245,
  545.3711679580864,
  357.0219363811122],
 [385.2763086761522,
  74.08556960975572,
  102.55989455322408,
  0.0,
  222.02158790787772,
  980.0419821624937,
  455.15431843362114,
  314.39083762393216],
 [519.1781416000524,
  265.90267575634203,
  324.5523437486846,
  222.02158790787772,
  0.0,
  1058.9894696910126,
  284.235650931963,
  323.9759381346695],
 [604.0116160731279,
  1034.6275191801828,
  955.6156714446245,
  980.0419821624937,
  1058.9894696910126,
  0.0,
  968.3856500652157,
  736.0410313007617],
 [570.6225847450158,
  519.8317632993619,
  545.3711679580

In [8]:
import numpy as np

In [9]:
cost=res
print(cost)
cost = cost.astype(np.int32)
print(cost)

[[   0.          433.14254286  351.63117602  385.27630868  519.1781416
   604.01161607  570.62258475  263.64143978]
 [ 433.14254286    0.           95.05472496   74.08556961  265.90267576
  1034.62751918  519.8317633   387.37657718]
 [ 351.63117602   95.05472496    0.          102.55989455  324.55234375
   955.61567144  545.37116796  357.02193638]
 [ 385.27630868   74.08556961  102.55989455    0.          222.02158791
   980.04198216  455.15431843  314.39083762]
 [ 519.1781416   265.90267576  324.55234375  222.02158791    0.
  1058.98946969  284.23565093  323.97593813]
 [ 604.01161607 1034.62751918  955.61567144  980.04198216 1058.98946969
     0.          968.38565007  736.0410313 ]
 [ 570.62258475  519.8317633   545.37116796  455.15431843  284.23565093
   968.38565007    0.          307.13124961]
 [ 263.64143978  387.37657718  357.02193638  314.39083762  323.97593813
   736.0410313   307.13124961    0.        ]]
[[   0  433  351  385  519  604  570  263]
 [ 433    0   95   74  265 10

In [10]:
n=8

In [11]:
edges = []
print(edges)

[]


In [12]:
for i in range(n):
    for j in range(n):
        if i<j:
            edges.append([i,j,cost[i][j]])
print(edges)

[[0, 1, 433], [0, 2, 351], [0, 3, 385], [0, 4, 519], [0, 5, 604], [0, 6, 570], [0, 7, 263], [1, 2, 95], [1, 3, 74], [1, 4, 265], [1, 5, 1034], [1, 6, 519], [1, 7, 387], [2, 3, 102], [2, 4, 324], [2, 5, 955], [2, 6, 545], [2, 7, 357], [3, 4, 222], [3, 5, 980], [3, 6, 455], [3, 7, 314], [4, 5, 1058], [4, 6, 284], [4, 7, 323], [5, 6, 968], [5, 7, 736], [6, 7, 307]]


In [13]:
edges = np.array(edges)

In [14]:
edges = edges[edges[:,2].argsort()]

In [15]:
print(edges)

[[   1    3   74]
 [   1    2   95]
 [   2    3  102]
 [   3    4  222]
 [   0    7  263]
 [   1    4  265]
 [   4    6  284]
 [   6    7  307]
 [   3    7  314]
 [   4    7  323]
 [   2    4  324]
 [   0    2  351]
 [   2    7  357]
 [   0    3  385]
 [   1    7  387]
 [   0    1  433]
 [   3    6  455]
 [   1    6  519]
 [   0    4  519]
 [   2    6  545]
 [   0    6  570]
 [   0    5  604]
 [   5    7  736]
 [   2    5  955]
 [   5    6  968]
 [   3    5  980]
 [   1    5 1034]
 [   4    5 1058]]


In [16]:
def findParent(u,parent):
  if parent[u-1] == -1:
    return u-1
  return findParent(parent[u-1],parent)

In [17]:
def Union(u,v,parent):
  parent[v-1] = u-1
  return

In [18]:
t = np.array([[0]*3 for i in range(n-1)])
t

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
parent = [-1]*n
parent
edges.shape

(28, 3)

In [20]:
def Kruskal(E,n,t):
  parent = [-1]*n
  i = 0
  j = -1 #traversing the edge matrix
  mincost = 0
  while (i < n-1) and (i < E.shape[0]):
    j+=1
    u = E[j][0]
    v = E[j][1]
    p = findParent(E[j][0],parent)
    q = findParent(E[j][1],parent)

    if p != q:
      i+=1
      t[i-1][0] = u
      t[i-1][1] = v
      t[i-1][2] = E[j][2]
      mincost+=E[j][2]
      Union(u,v,parent)

  if i!=n-1:
    print("No spanning tree")
  else:
    print("Mincost : ",mincost)
    print(t)
Kruskal(edges,n,t)

Mincost :  1510
[[  1   3  74]
 [  1   2  95]
 [  3   4 222]
 [  0   7 263]
 [  1   4 265]
 [  4   6 284]
 [  6   7 307]]
